#
# @file        desktop-unit-test.yml
# @copyright   2022 Andrew MacIsaac
# @remark
#      SPDX-License-Identifier: MPL-2.0
#
# @brief       Build and run the unit tests on the three desktop platforms.
#
name: Desktop Unit Tests

# Trigger normal CMake test builds for all branches on push, PR, and manual
# trigger.
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  # Set CMake build type.
  BUILD_TYPE: Debug

# Run the unit test builds for each platform.
jobs:
  unit-test:
    name:     Unit Test (${{ runner.os }})
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Install dependencies.
      - name: Install APT dependencies
        if: matrix.os == 'ubuntu-latest'
        run:  sudo apt-get install -y ninja-build
      - name: Install Homebrew dependencies
        if: matrix.os == 'macos-latest'
        run:  brew install ninja

      # Check out the code.
      - name: Clone ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          path: repo

      # Create build directory.
      - name: Create build environment
        run:  cmake -E make_directory '${{ github.workspace }}/repo/build'

      # Run CMake configuration.
      - name:               Configure CMake
        if: matrix.os != 'windows-latest'
        working-directory:  ${{ github.workspace }}/repo/build
        run:                cmake .. -G Ninja -DCMAKE_BUILD_TYPE="${BUILD_TYPE}"
      - name:               Configure CMake
        if: matrix.os == 'windows-latest'
        working-directory:  ${{ github.workspace }}/repo/build
        run:                cmake .. -G 'Visual Studio 16 2019' -A x64

      # Build the library.
      - name:               Build library
        working-directory:  ${{ github.workspace }}/repo/build
        run:                cmake --build . --config "${BUILD_TYPE}"

      # Run the unit tests.
      - name:               Run tests
        working-directory:  ${{ github.workspace }}/repo/build
        run: |
          ctest                             \
            --build-config "${BUILD_TYPE}"  \
            --test-action test              \
            --output-on-failure             \
            --parallel 4
